[package]
name = "b64"
version = "0.0.1"
authors = ["Narasimha1997 <yogaimpression@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
boson = { path = "../../boson" }
base64 = "0.13.0"